name: Search for tags in file

on:
  push:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secretsGITHUB_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  search-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read file and search for tags
        run: |
          # Replace these values with your own
          FILENAME=hash.txt
          TAGS=sonal,raghuvanshi,jaswinder

          # Read the file contents into a variable
          CONTENT=$(cat $FILENAME)

          # Loop over the tags and check if they exist in the file contents
          for TAG in $(echo $TAGS | tr ',' ' '); do
            if echo $CONTENT | grep -q $TAG; then
              echo "Found tag $TAG in $FILENAME" > tag.txt
            fi
          done
      
      - name: Add changes to GIT
        run: |
          git config --global user.email "sonalraghuvanshi15@gmail.com"
          git config --global user.name "SonalRaghuvanshi"
          git add tag.txt
          git commit -m "Added the tag list"
          
      - name: Push Changes
        run: |
          git push origin master
